# Generated by Django 2.1.5 on 2019-02-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('files', models.FileField(upload_to='pdf/')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
