# Generated by Django 2.1.5 on 2019-02-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
