# Generated by Django 2.1.5 on 2019-02-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20190210_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='no_of_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
