# Generated by Django 2.1.5 on 2019-02-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospitals_no_of_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='no_of_rooms',
            new_name='no_of_beds',
        ),
    ]
